#!/bin/sh
#-
# Copyright (c) 2013 Nathan Whitehorn
# Copyright (c) 2013-2015 Devin Teske
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$
#
############################################################ INCLUDES

BSDCFG_SHARE="/usr/share/bsdconfig"
. "$BSDCFG_SHARE/common.subr" || exit 1
f_dprintf "%s: loading includes..." "$0"
f_include $BSDCFG_SHARE/dialog.subr
f_include $BSDCFG_SHARE/variable.subr

############################################################ GLOBALS

: "${TMPDIR:="/tmp"}"

############################################################ FUNCTIONS

error()
{
	bsdinstall umount
	exit 1
}

############################################################ MAIN

set -e
trap error EXIT

SCRIPT="$1"
shift

f_dprintf "Began Installation at %s" "$( date )"
rm -rf "$BSDINSTALL_TMPETC"
mkdir "$BSDINSTALL_TMPETC"

split -a 2 -p '^#!.*' "$SCRIPT" "$TMPDIR/bsdinstall-installscript-"

. "$TMPDIR/bsdinstall-installscript-aa"
: "${DISTRIBUTIONS="kernel.txz base.txz"}"
export DISTRIBUTIONS
export BSDINSTALL_DISTDIR

# Mount filesystems
bsdinstall mount

# Fetch missing distribution files, if any
exec 5>&1
BSDINSTALL_DISTDIR="$("$(dirname "$0")/fetchmissingdists" 2>&1 1>&5)"
FETCH_RESULT=$?
exec 5>&-

[ $FETCH_RESULT -ne 0 ] && error "Could not fetch remote distributions"

# Unpack distributions
bsdinstall checksum
for set in $DISTRIBUTIONS; do
	tar -xf "$BSDINSTALL_DISTDIR/$set" -C "$BSDINSTALL_CHROOT" --exclude boot/efi
	mkdir -p "$BSDINSTALL_CHROOT/boot/efi"
done

cp "$PATH_FSTAB" "$BSDINSTALL_CHROOT/etc/fstab"
cat /etc/resolv.conf > "$BSDINSTALL_CHROOT/etc/resolv.conf"

# Run post-install script
if [ -f "$TMPDIR/bsdinstall-installscript-ab" ]; then
	cp "$TMPDIR/bsdinstall-installscript-ab" "$BSDINSTALL_CHROOT/tmp/installscript"
	chmod a+x "$BSDINSTALL_CHROOT/tmp/installscript"
	chroot "$BSDINSTALL_CHROOT" /tmp/installscript "$@" 2>&1
	rm "$BSDINSTALL_CHROOT/tmp/installscript"
fi

bsdinstall entropy
bsdinstall umount

f_dprintf "Installation Completed at %s" "$( date )"

trap - EXIT
exit "$SUCCESS"

################################################################################
# END
################################################################################
